export const types = {
    // Sync
    SET_USER: "SET_USER",
    LOGOUT: "LOGOUT",
    INITIALIZED: "INITIALIZED",

    // Async    
    LOGIN_ASYNC: "LOGIN_ASYNC",
    LOGOUT_ASYNC: "LOGOUT_ASYNC",
    AUTH_CHANGED_ASYNC: "AUTH_CHANGED_ASYNC",
    UPDATE_PROFILE_ASYNC: "UPDATE_PROFILE_ASYNC",
};
