export const types = {
    SET_CHOICE: 'SET_CHOICE',
    INVITE_OPPONENT: 'INVITE_OPPONENT',    
    CHANGE_GAME_TYPE: 'CHANGE_GAME_TYPE',
    PLAY_WITH_PC: 'PLAY_WITH_PC',
    RESET_GAME: 'RESET_GAME',
    PLAY_WITH_USER: 'PLAY_WITH_USER',

    START_GAME:    'START_GAME',    
    WIN_GAME:      'WIN_GAME',
    DRAW_GAME:      'DRAW_GAME',    


    INVITE_OPPONENT_TO_GAME_ASYNC: 'INVITE_OPPONENT_TO_GAME_ASYNC',
    REMOVE_GAME_ASYNC: 'REMOVE_GAME_ASYNC',
    SET_CHOICE_TO_DB_ASYNC: 'SET_CHOICE_TO_DB_ASYNC',
    SUBSCRIBE_FOR_GAMES: 'SUBSCRIBE_FOR_GAMES',
    SUBSCRIBE_FOR_CURRENT_GAME: 'SUBSCRIBE_FOR_CURRENT_GAME',
};